apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: gitserver
        image: k8s.gcr.io/git-sync/git-sync:v3.2.2
        volumeMounts:
        - name: volume
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/abha-sflscientific/testing.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEST
          value: work
      - name: minimal-notebook
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
        volumeMounts:
          - name: volume
            mountPath: /home/jovyan/
      - name: minimal-notebook2
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8889
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
        volumeMounts:
          - name: volume
            mountPath: /home/jovyan/
      volumes:
        - name: volume
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    name: book-1
    nodePort: 30040
    port: 8888
    targetPort: 8888
  - protocol: TCP
    name: book-2
    nodePort: 30041
    port: 8889
    targetPort: 8889
